#!/bin/bash
curl -X POST http://localhost:8080/api/signup -H "Content-Type: application/json" -d '{"id": 1, "firstName": "John", "lastName": "Doe","password": "abc", "dob": 1523985843719}'
echo ""
curl -X POST http://localhost:8080/api/signup -H "Content-Type: application/json" -d '{"id": 2, "firstName": "Mary", "lastName": "Jane", "password": "abc", "dob": 1523985843719}'
echo ""
curl -X POST http://localhost:8080/api/newRelationship -H "Content-Type: application/json" -d '{"personID": 1, "friendID": 2}'
echo ""
curl -X POST http://localhost:8080/api/login -H "Content-Type: application/json" -d '{"id": 1, "password": "abc"}'



